#!/bin/bash

# return id of desktop which distance is $1 from current desktop
#     if current desktop = 1 and you pass 1 as argument, will print 2 to output,
#     that is if there is enough desktops (3 in this case). If not, it wraps around
#     and returns 0

ADD=0
if [[ $# -gt 0 ]]; then
    ADD=$1
fi

N=$(xdotool get_num_desktops)
C=$(xdotool get_desktop)
D=$((($C + $ADD) % $N))

if [[ $D -lt 0 ]]; then
    D=$(($D + $N))
fi

echo $D
