#!/bin/bash

sxhkd &

feh --bg-fill ~/Pictures/wall.jpg &

xdotool set_num_desktops 5

swmctl config border 1 B0BEC5 00BCD4 F44336
swmctl config border-top 3 B0BEC5 00BCD4 F44336

swmctl config font "/usr/share/fonts/TTF/JetBrainsMono-Bold.ttf"
swmctl config info-bg-color 00BCD4
swmctl config info-text-color FFFFFF

swmctl config move-drag-shortcut Mod1-1
swmctl config resize-drag-shortcut Mod1-3

swmctl group mode auto # or sticky

swmctl group names 1 2 3 4 5 6 7 8 9

