#!/bin/bash

sxhkd &

feh --bg-fill ~/Pictures/wall.jpg &

xdotool set_num_desktops 5

swmctl set-desktop-names 1 2 3 4 5 6 7 8 9

swmctl config border 1 B0BEC5 00BCD4 F44336
swmctl config border-top 3 B0BEC5 00BCD4 F44336

swmctl config move-drag-shortcut Mod1-1
swmctl config resize-drag-shortcut Mod1-3

