name: Build and test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Cache Go modules
      uses: actions/cache@v1
      env:
        cache-name: cache-go-modules
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build swm
      run: go build github.com/janbina/swm/cmd/swm

    - name: Build swmctl
      run: go build github.com/janbina/swm/cmd/swmctl

    - name: Install Xvfb
      run: sudo apt-get install xvfb

    - name: Test
      working-directory: test
      run: ./run.sh
      env:
        DISPLAY: :111
